part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const SHOP = _Paths.SHOP;
  static const LOGIN = _Paths.LOGIN;
  static const REGISTER = _Paths.REGISTER;
  static const VERIFY_METHOD = _Paths.VERIFY_METHOD;
  static const PROFILE = _Paths.PROFILE;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const SETTING_LOGOUT = _Paths.SETTING_LOGOUT;
  static const HOME = _Paths.HOME;
  static const CART = _Paths.CART;
  static const FILTER = _Paths.FILTER;
  static const PRODUCT_LIST_SHOP = _Paths.PRODUCT_LIST_SHOP;
  static const ADD_PRODUCT = _Paths.ADD_PRODUCT;
  static const EDIT_PRODUCT = _Paths.EDIT_PRODUCT;
  static const ADD_BANNER = _Paths.ADD_BANNER;
  static const PRODUCT_FORM = _Paths.PRODUCT_FORM;
  static const SHOP_REGISTER = _Paths.SHOP_REGISTER;
  static const PRODUCT_DISCOUNT = _Paths.PRODUCT_DISCOUNT;
  static const SHOP_DASHBOARD = _Paths.SHOP_DASHBOARD;
  static const PRODUCT_DETAIL = _Paths.PRODUCT_DETAIL;
  static const PRODUCT_SELECTION = _Paths.PRODUCT_SELECTION;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const RESET_PASSWORD = _Paths.RESET_PASSWORD;
  static const OTP_VERIFICATION = _Paths.OTP_VERIFICATION;
  static const PASSWORD_VERIFICATION = _Paths.PASSWORD_VERIFICATION;
  static const USER_INFO = _Paths.USER_INFO;
  static const SPLASH_SCREEN = _Paths.SPLASH_SCREEN;
  static const CHECKOUT = _Paths.CHECKOUT;
  static const SHOP_ADD_DISCOUNT = _Paths.SHOP_ADD_DISCOUNT;
  static const SHOP_VOUCHER_LIST = _Paths.SHOP_VOUCHER_LIST;
  static const SHOP_VOUCHER_ADD = _Paths.SHOP_VOUCHER_ADD;
  static const SHOP_DETAIL = _Paths.SHOP_DETAIL;
  static const SHOP_PRODUCT_LIST = _Paths.SHOP_PRODUCT_LIST;
  static const MY_ORDER = _Paths.MY_ORDER;
  static const RECOMMENDED_PRODUCTS = _Paths.RECOMMENDED_PRODUCTS;
  static const CHECK_OUT = _Paths.CHECK_OUT;
  static const SHOP_ORDER = _Paths.SHOP_ORDER;
  static const RETURN_ORDER_DETAIL_PAGE = _Paths.RETURN_ORDER_DETAIL_PAGE;
  static const VOUCHER_LIST = _Paths.VOUCHER_LIST;
  static const ADD_VOUCHER = _Paths.ADD_VOUCHER;
  static const QR_PAYMENT = _Paths.QR_PAYMENT;
  static const SEARCH_SCREEN = _Paths.SEARCH_SCREEN;
  static const SHOP_PROFILE = _Paths.SHOP_PROFILE;
  static const USER_VIEW_SHOP_DETAIL = _Paths.USER_VIEW_SHOP_DETAIL;
  static const SHOP_REPORT = _Paths.SHOP_REPORT;
  static const SEND_REPORT = _Paths.SEND_REPORT;
  static const SHOP_REPORT_LIST = _Paths.SHOP_REPORT_LIST;
}

abstract class _Paths {
  _Paths._();
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const VERIFY_METHOD = '/verify-method';
  static const PROFILE = '/profile';
  static const EDIT_PROFILE = '/edit-profile';
  static const CHANGE_PASSWORD = '/change-password';
  static const SETTING_LOGOUT = '/setting-logout';
  static const HOME = '/home';
  static const CART = '/cart';
  static const FILTER = '/filter';
  static const SHOP = '/shop';
  static const PRODUCT_LIST_SHOP = '/product-list-shop';
  static const ADD_PRODUCT = '/add-product';
  static const EDIT_PRODUCT = '/edit-product';
  static const ADD_BANNER = '/add-banner';
  static const PRODUCT_FORM = '/product-form';
  static const PRODUCT_DETAIL = '/product-detail';
  static const PRODUCT_SELECTION = '/product-selection';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const RESET_PASSWORD = '/reset-password';
  static const OTP_VERIFICATION = '/otp-verification';
  static const PASSWORD_VERIFICATION = '/password-verification';
  static const USER_INFO = '/user-info';
  static const SPLASH_SCREEN = '/splash-screen';
  static const CHECKOUT = '/checkout';
  static const MY_ORDER = '/my-order';
  static const RECOMMENDED_PRODUCTS = '/recommended-products';
  static const CHECK_OUT = '/check-out';
  static const SHOP_ORDER = '/shop-order';
  static const RETURN_ORDER_DETAIL_PAGE = '/return-order-detail-page';
  static const VOUCHER_LIST = '/voucher-list';
  static const ADD_VOUCHER = '/add-voucher';
  static const QR_PAYMENT = '/qr-payment';
  static const SEARCH_SCREEN = '/search-screen';
  static const SHOP_PROFILE = '/shop-profile';
  static const USER_VIEW_SHOP_DETAIL = '/user-view-shop-detail';
  static const SHOP_REPORT = '/shop-report';
  static const SEND_REPORT = '/send-report';
  static const SHOP_REPORT_LIST = '/shop-report-list';
  static const SHOP_REGISTER = '/shop-register';
  static const PRODUCT_DISCOUNT = '/product-discount';
  static const SHOP_DASHBOARD = '/shop-dashboard';
  static const SHOP_ADD_DISCOUNT = '/shop-add-discount';
  static const SHOP_VOUCHER_LIST = '/shop-voucher-list';
  static const SHOP_VOUCHER_ADD = '/shop-voucher-add';
  static const SHOP_DETAIL = '/shop-detail';
  static const SHOP_PRODUCT_LIST = '/shop-product-list';
}
